services:
  nginx:
    image: nginx:alpine
    ports: 
      - 80:80
      - 443:443 
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginx-net 
    container_name: nginx-main

networks:
  nginx-net:
    external: true
